### PR TITLE
Updated vfdeps-win

### PR DESCRIPTION
**Pull request by NielsMommen**
- Updated to 64-bit build
  - `libxml2` compiled from sources
  - `gtksourceview-2` compiled from sources
- Removed required `MSVC` installation: `cap'n proto` is now built with `MinGW` toolchain
- Updated `GitHub` actions runner images
- Updated `OCaml` to `4.14.0`
- Updated other dependencies to recent versions
- Added dependencies to support [`ppx_parser`](https://github.com/NielsMommen/ppx_parser) in the future: a replacement for `Camlp4`

### CODE REVIEW

**Comment by NielsMommen** [comment]
- [`VeriFast` source code](https://github.com/NielsMommen/verifast/tree/vfdeps) using this `vfdeps-win` package
- [`VeriFast` build](https://github.com/NielsMommen/verifast/actions/runs/4731543602) using this `vfdeps-win` package

**Comment by NielsMommen** [comment]
The `VeriFast` build using this `vfdeps` package does not link to `zstd` anymore. I had to change a configuration option when building [`vf-llvm-clang-build`](https://github.com/NielsMommen/vf-llvm-clang-build) to disable this library. `llvm/clang` has also been updated to version 16.0.1 in this latter package.

The `cap'n proto` build has also been patched to make sure it does not require `libz` anymore.

I also transitioned to the new parser syntax:
* [`VeriFast` source code](https://github.com/NielsMommen/verifast/tree/vfdeps) using this `vfdeps` package and new parser syntax
* [`VeriFast` build](https://github.com/NielsMommen/verifast/actions/runs/4756655481) using this `vfdeps` package and new parser syntax

**Comment by btj** [comment]
Did you test (= test suite and vfide) the binary packages in a clean Windows environment for missing dependencies?

**Comment by NielsMommen** [comment]
> Did you test (= test suite and vfide) the binary packages in a clean Windows environment for missing dependencies?

Tested on a fresh Windows 10 VM

**Comment by btj** [comment]
Excellent work, Niels! Many thanks!!

**Pull request merged**
